2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_setup.py:_flush():68] Current SDK version is 0.19.10
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_setup.py:_flush():68] Configure stats pid to 12904
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_setup.py:_flush():68] Loading settings from C:\Users\oplab\.config\wandb\settings
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_setup.py:_flush():68] Loading settings from C:\Users\oplab\Desktop\Tony\Thyroid\code\wandb\settings
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\oplab\Desktop\Tony\Thyroid\code\wandb\run-20250430_095527-f06or45x\logs\debug.log
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\oplab\Desktop\Tony\Thyroid\code\wandb\run-20250430_095527-f06or45x\logs\debug-internal.log
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000200520EDA00>
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:init():852] calling init triggers
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'image_size': 128, 'learning_rate': 0.001, 'epochs': 20, 'batch_size': 8, '_wandb': {}}
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:init():893] starting backend
2025-04-30 09:55:27,614 INFO    MainThread:12904 [wandb_init.py:init():897] sending inform_init request
2025-04-30 09:55:27,635 INFO    MainThread:12904 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-04-30 09:55:27,638 INFO    MainThread:12904 [wandb_init.py:init():907] backend started and connected
2025-04-30 09:55:27,642 INFO    MainThread:12904 [wandb_run.py:_label_probe_notebook():1369] probe notebook
2025-04-30 09:55:27,643 INFO    MainThread:12904 [wandb_run.py:_label_probe_notebook():1379] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-04-30 09:55:27,643 INFO    MainThread:12904 [wandb_init.py:init():1002] updated telemetry
2025-04-30 09:55:27,677 INFO    MainThread:12904 [wandb_init.py:init():1026] communicating run to backend with 90.0 second timeout
2025-04-30 09:55:28,407 INFO    MainThread:12904 [wandb_init.py:init():1101] starting run threads in backend
2025-04-30 09:55:28,595 INFO    MainThread:12904 [wandb_run.py:_console_start():2566] atexit reg
2025-04-30 09:55:28,595 INFO    MainThread:12904 [wandb_run.py:_redirect():2414] redirect: wrap_raw
2025-04-30 09:55:28,595 INFO    MainThread:12904 [wandb_run.py:_redirect():2483] Wrapping output streams.
2025-04-30 09:55:28,595 INFO    MainThread:12904 [wandb_run.py:_redirect():2506] Redirects installed.
2025-04-30 09:55:28,596 INFO    MainThread:12904 [wandb_init.py:init():1147] run started, returning control to user process
2025-04-30 09:55:28,596 INFO    MainThread:12904 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-04-30 09:56:08,866 INFO    MainThread:12904 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-04-30 09:56:08,866 INFO    MainThread:12904 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-04-30 09:56:08,884 INFO    MainThread:12904 [wandb_run.py:_finish():2314] finishing run s960068sss-ucl/thyroid/f06or45x
2025-04-30 09:56:08,886 INFO    MainThread:12904 [jupyter.py:save_history():477] not saving jupyter history
2025-04-30 09:56:08,886 INFO    MainThread:12904 [jupyter.py:save_ipynb():401] not saving jupyter notebook
2025-04-30 09:56:08,886 INFO    MainThread:12904 [wandb_init.py:_jupyter_teardown():628] cleaning up jupyter logic
2025-04-30 09:56:08,886 INFO    MainThread:12904 [wandb_run.py:_atexit_cleanup():2531] got exitcode: 0
2025-04-30 09:56:08,887 INFO    MainThread:12904 [wandb_run.py:_restore():2513] restore
2025-04-30 09:56:08,887 INFO    MainThread:12904 [wandb_run.py:_restore():2519] restore done
2025-04-30 09:56:37,664 WARNING MsgRouterThr:12904 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [WinError 10054] 遠端主機已強制關閉一個現存的連線。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
          ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-04-30 09:56:37,672 INFO    MsgRouterThr:12904 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 2 handles.
2025-04-30 09:56:37,680 WARNING MainThread:12904 [wandb_init.py:init():1654] [no run ID] interrupted
Traceback (most recent call last):
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_init.py", line 1650, in init
    return wi.init(run_settings, run_config, run_printer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_init.py", line 873, in init
    self._wl.finish_all_active_runs()
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_setup.py", line 150, in finish_all_active_runs
    run.finish()
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 503, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 2302, in finish
    return self._finish(exit_code)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 2330, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 2543, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\wandb_run.py", line 2799, in _on_finish
    wait_with_progress(
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\mailbox\wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\mailbox\wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\site-packages\wandb\sdk\lib\asyncio_compat.py", line 30, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\concurrent\futures\_base.py", line 451, in result
    self._condition.wait(timeout)
  File "C:\Users\oplab\anaconda3\envs\thyroid\Lib\threading.py", line 355, in wait
    waiter.acquire()
KeyboardInterrupt
